[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashBootstrapComponents = "1b08a953-4be3-4667-9a23-fa6d05876a1e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkObservables = "8710efd8-4ad6-11eb-33ea-2d5ceb25a41c"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
